services:

  backend_app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  redis:
    image: redis
    ports:
      - 6381:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  celery:
    build: .
    command: celery -A project_core worker --without-gossip -l INFO
    # env_file:
    #   - ./.env
    # depends_on:
    #   - redis

  app_queue:
    build: .
    command: python consumer.py