# Generated by Django 4.2 on 2023-05-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reference_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='User Reference ID'),
        ),
    ]
