# Generated by Django 4.2 on 2023-05-13 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow_app', '0002_user_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pix',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])], verbose_name='profile image'),
        ),
    ]
