# Generated by Django 4.2 on 2023-05-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow_app', '0004_remove_user_address_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='Hello User', max_length=150, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lga',
            field=models.CharField(default='lga', max_length=150, verbose_name='local govt area'),
        ),
    ]
