# Generated by Django 4.2 on 2023-10-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow_app', '0006_transaction_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='product_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seller_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
