# Generated by Django 4.2 on 2023-11-01 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escrow_app', '0007_alter_transaction_product_total_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_product', to='escrow_app.transaction')),
            ],
        ),
    ]
