# Generated by Django 4.2 on 2023-11-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow_app', '0008_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Transaction_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Open', max_length=200),
        ),
    ]
