# Generated by Django 4.2 on 2023-11-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow_app', '0009_alter_transaction_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Created', 'Order Created'), ('Payment Completed', 'Payment Completed'), ('Order Canceled', 'Order Canceled')], max_length=200),
        ),
    ]
